Add working version of raspberrypi rfid_tuer
stuvusIT/rfid_tuer_ansible pull request #1
Opened 2018-07-28 22:53 UTC by Scriptkiddi

2018-07-28 23:04 UTC, dasJ requested changes
Please don't run as root :)

2018-07-28 23:21 UTC, Scriptkiddi commented
pls rereview

2018-07-31 08:06 UTC, Scriptkiddi commented
pls rereview

2018-08-02 21:50 UTC, dasJ approved these changes

2018-08-02 21:50 UTC, merged